Repository adam-broussard/bestreads, pull requests merged in 2022-04, with the labels that each got.

#14 Added a description to the README.
  README.md
Labels: documentation

#18 Adds a function that extracts genre and votes from the dataset
  .gitignore
  bestreads/__init__.py
  bestreads/dataset.py
  dataset_ops.py
  notebooks/0_data_summary.ipynb
  plotter.py
  setup.py
Labels: enhancement

#19 Desc english
  .github/workflows/pylint.yml
  .gitignore
  bestreads/text.py
  setup.py
Labels: enhancement

#21 Processes text in book descriptions
  .gitignore
  bestreads/dataset.py
  bestreads/text.py
  notebooks/0_data_summary.ipynb
  setup.py
Labels: enhancement

#26 Text processing and example notebook
  bestreads/text.py
  notebooks/1_Analysis.ipynb
Labels: enhancement

#33 Bug Fixes and Text Preprocessing and Caching
  bestreads/__init__.py
  bestreads/text.py
  notebooks/1_Preprocessing.ipynb
  notebooks/2_Analysis.ipynb
Labels: bug, enhancement

#36 Fixed preprocessed data reading and writing
  notebooks/1_Preprocessing.ipynb
  notebooks/2_Analysis.ipynb
Labels: bug, enhancement

#40 Fixed errors and improper sorting
  bestreads/text.py
Labels: bug

#41 Selecting only well-measured genres and adding validation
  bestreads/text.py
  notebooks/1_Preprocessing_and_Training.ipynb
  notebooks/2_Analysis.ipynb
  notebooks/2_Analysis_and_Validation.ipynb
Labels: bug, enhancement
